"""add document parsing fields

Revision ID: 9bfb4e4f9fe7
Revises: 0a8e1d7ce71e
Create Date: 2026-08-20 17:20:32.307004
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "9bfb4e4f9fe7"
down_revision: str | None = "0a8e1d7ce71e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply schema changes."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "document_pages",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("page_number", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("character_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
            name=op.f("fk_document_pages_document_id_documents"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_document_pages")),
        sa.UniqueConstraint(
            "document_id", "page_number", name=op.f("uq_document_pages_document_id")
        ),
    )
    with op.batch_alter_table("document_pages", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_document_pages_document_id"), ["document_id"], unique=False
        )

    with op.batch_alter_table("documents", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("page_count", sa.Integer(), server_default=sa.text("0"), nullable=False)
        )
        batch_op.add_column(sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True))
        batch_op.create_unique_constraint(
            "uq_documents_kb_file_hash", ["knowledge_base_id", "file_hash"]
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert schema changes."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("documents", schema=None) as batch_op:
        batch_op.drop_constraint("uq_documents_kb_file_hash", type_="unique")
        batch_op.drop_column("processed_at")
        batch_op.drop_column("page_count")

    with op.batch_alter_table("document_pages", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_document_pages_document_id"))

    op.drop_table("document_pages")
    # ### end Alembic commands ###
